apiVersion: v1
kind: Service
metadata:
  name: sample-ecommerce-nodejs-app-service
  labels:
    apps: myapps
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    apps: myapps