apiVersion: apps/v1
kind: Deployment  
metadata:
  name: Sample-Ecommerce-Nodejs-App
  labels:
    apps: myapps


spec:
  replicas: 2
  selector:
    matchLabels:
      apps: myapps
  template:
    metadata:
      labels:
        apps: myapps
    spec:
      containers:
        - name: ecommerce-nodejs-app container
          # image: "nuthan0530/sample-ecommerce-nodejs-app:latest"
          image: "nuthan0530/sample-ecommerce-nodejs-app:latest"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
              
          